name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Create the output directory and ensure it has an __init__.py file
        mkdir -p curriculum_curator/output
        touch curriculum_curator/output/__init__.py
        # Install the package and dependencies
        pip install -e ".[dev]"
        pip install pytest pytest-cov
    - name: Lint with pre-commit
      uses: pre-commit/action@v3.0.0
    - name: Test with pytest
      run: |
        pytest --cov=curriculum_curator
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        verbose: true
